image: mcr.microsoft.com/dotnet/core/sdk:3.1

stages:
    - test

test:
    stage: test
    script: 
        - "cd DevOpsBlazor.UnitTests/"
        - "dotnet build --configuration Release"
        - "dotnet test --configuration Release"

